### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/VPV#81]
We're getting a null pointer when we create a new project.

```
Caused by: java.lang.NullPointerException
	at vpvgui.gui.splash.SwitchScreens.setModelXYBounds(SwitchScreens.java:115)
	at vpvgui.gui.splash.SwitchScreens.createNewProject(SwitchScreens.java:58)
	at vpvgui.gui.splash.SplashPresenter.newProject(SplashPresenter.java:72)
	... 58 more
```

This is the method causing the Null pointer and I'm also proposing a solution which worked in my case (commenting the line as below)
```
// vpvgui.gui.splash.SwitchScreens class
public void createNewProject(String name){
        VPVMainView appView = new VPVMainView();
        VPVMainPresenter presenter = (VPVMainPresenter) appView.getPresenter();
//        this.primarystage.setMinWidth(1000);
//        this.primarystage.setWidth(1600);
        Model model = new Model();
        model.setProjectName(name);
        model.setDefaultValues();
        model.setXdim(screenWidth);
        model.setYdim(screenHeight);
        logger.error(String.format("Setting dimensions to x=%d y=%d",screenWidth,screenHeight ));
        presenter.setModel(model);
        Scene scene = new Scene(appView.getView());
        this.primarystage.setScene(scene);
        this.primarystage.centerOnScreen();
        this.primarystage.setTitle(String.format("Viewpoint Viewer: %s",name));
        // The commented line is causing null pointer during creation of the new project when the hidden file is not
        // yet present in the user's home directory.
        // This is not necessary, since we're adjusting the bounds 7 lines above this one. Is that correct?
        // setModelXYBounds();
        this.primarystage.show();
    }
```

**Comment by pnrobinson** [comment]
Fixed the bug, but the window that appears for new model is too small --need to set the same as with the old models.

**Comment by pnrobinson** [comment]
The size is now initialized correctly, I am closing this.
